baseURL = "https://www.heyphilipp.com/"
languageCode = "en-us"
title = "Philipp Pitchford"
theme = "ritzy"

[params]
    author = "Philipp Pitchford"
    description = "Philipp Pitchford's personal website"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
